// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBm8OwLzinJGdZSgfhGREWMhCehC-YrmxE',
    appId: '1:1005563889129:web:3397aa31db091f457eb778',
    messagingSenderId: '1005563889129',
    projectId: 'ai-finance-tracker-6e907',
    authDomain: 'ai-finance-tracker-6e907.firebaseapp.com',
    storageBucket: 'ai-finance-tracker-6e907.firebasestorage.app',
    measurementId: 'G-13BSJEF81N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZE8haOV90gdA2bFgk65VQMC-t9JhvD78',
    appId: '1:1005563889129:android:0970d4e7326581577eb778',
    messagingSenderId: '1005563889129',
    projectId: 'ai-finance-tracker-6e907',
    storageBucket: 'ai-finance-tracker-6e907.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfVsOcJPe-Jc1SHdxmdn1A_gQotl-2Qo',
    appId: '1:1005563889129:ios:d80d531c01efe0e37eb778',
    messagingSenderId: '1005563889129',
    projectId: 'ai-finance-tracker-6e907',
    storageBucket: 'ai-finance-tracker-6e907.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDfVsOcJPe-Jc1SHdxmdn1A_gQotl-2Qo',
    appId: '1:1005563889129:ios:d80d531c01efe0e37eb778',
    messagingSenderId: '1005563889129',
    projectId: 'ai-finance-tracker-6e907',
    storageBucket: 'ai-finance-tracker-6e907.firebasestorage.app',
    iosBundleId: 'com.example.testApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBm8OwLzinJGdZSgfhGREWMhCehC-YrmxE',
    appId: '1:1005563889129:web:b7d3981ab79c8b757eb778',
    messagingSenderId: '1005563889129',
    projectId: 'ai-finance-tracker-6e907',
    authDomain: 'ai-finance-tracker-6e907.firebaseapp.com',
    storageBucket: 'ai-finance-tracker-6e907.firebasestorage.app',
    measurementId: 'G-2W6HX8CZG4',
  );
}
